package cn.blog2.entity;

import java.util.Date;

public class Article extends Base {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.ID
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.TITLE
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	private String title;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.DESCRIPTION
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	private String description;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.CREATETIME
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	private Date createtime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.AUTHOR
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	private Long author;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.CONTENT
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	private String content;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ARTICLE.CONTENT
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	private String md;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.ID
	 *
	 * @return the value of ARTICLE.ID
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.ID
	 *
	 * @param id
	 *            the value for ARTICLE.ID
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.TITLE
	 *
	 * @return the value of ARTICLE.TITLE
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.TITLE
	 *
	 * @param title
	 *            the value for ARTICLE.TITLE
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.DESCRIPTION
	 *
	 * @return the value of ARTICLE.DESCRIPTION
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.DESCRIPTION
	 *
	 * @param description
	 *            the value for ARTICLE.DESCRIPTION
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.CREATETIME
	 *
	 * @return the value of ARTICLE.CREATETIME
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.CREATETIME
	 *
	 * @param createtime
	 *            the value for ARTICLE.CREATETIME
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.AUTHOR
	 *
	 * @return the value of ARTICLE.AUTHOR
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public Long getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.AUTHOR
	 *
	 * @param author
	 *            the value for ARTICLE.AUTHOR
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public void setAuthor(Long author) {
		this.author = author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.CONTENT
	 *
	 * @return the value of ARTICLE.CONTENT
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.CONTENT
	 *
	 * @param content
	 *            the value for ARTICLE.CONTENT
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ARTICLE.CONTENT
	 *
	 * @return the value of ARTICLE.CONTENT
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public String getMd() {
		return md;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ARTICLE.CONTENT
	 *
	 * @param content
	 *            the value for ARTICLE.CONTENT
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	public void setMd(String content) {
		this.md = md == null ? null : md.trim();
	}
}