package cn.blog2.dao;

import java.util.List;
import java.util.Map;

public interface ArticleMapper {
	/**
	 * 用户注册
	 * 
	 * @author hehao
	 * @param queryMap
	 * @return int
	 */
	int userRegist(Map<String, Object> queryMap);

	/**
	 * 用户角色注册
	 * 
	 * @author hehao
	 * @param queryMap
	 * @return int
	 */
	int userRoleRegist(Map<String, Object> queryMap);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ARTICLE
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ARTICLE
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	int insert(Map<String, Object> queryMap);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ARTICLE
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	Map<String, Object> selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ARTICLE
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	List<Map<String, Object>> selectAll(Map<String, Object> queryMap);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ARTICLE
	 *
	 * @mbg.generated Fri Mar 17 14:38:16 SGT 2017
	 */
	int updateByPrimaryKey(Map<String, Object> queryMap);
}